# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 13:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='users.Department', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='position',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='users.Position', verbose_name='Reports To'),
        ),
    ]
