# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170703_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Job Positions', 'verbose_name_plural': 'Job Positions'},
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The parent department', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='users.Department', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='position',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The parent Job Position', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='users.Position', verbose_name='Reports To'),
        ),
    ]
