# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170703_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name', 'user__email'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
    ]
