# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 13:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='strategy.Objective', verbose_name='Contributes to'),
        ),
    ]
