# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20170409_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='best',
            field=models.IntegerField(choices=[(1, '1'), (5, '5')], default=5, help_text='Which value represents the best rating', max_length=1, verbose_name='Best Rating'),
        ),
    ]
