# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_best'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='best',
            field=models.IntegerField(choices=[(1, '1'), (5, '5')], default=5, help_text='Which value represents the best rating', verbose_name='Best Rating'),
        ),
    ]
