# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Key Performance Indicator')),
                ('measure', models.CharField(max_length=255, verbose_name='Measure')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('perspective', models.CharField(choices=[('1', 'Financial'), ('2', 'Customer'), ('3', 'Internal Process'), ('4', 'Learning & Growth')], max_length=1, verbose_name='Perspective')),
                ('baseline', models.DecimalField(decimal_places=2, default=0, help_text='', max_digits=64, verbose_name='Base Line')),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=64, verbose_name='Target')),
                ('unit', models.CharField(choices=[('1', 'Value'), ('12', 'Number'), ('3', 'Percentage'), ('2', 'Ratio'), ('10', 'Score'), ('11', 'Rating'), ('4', 'Second(s)'), ('5', 'Minute(s)'), ('6', 'Hour(s)'), ('7', 'Day(s)'), ('8', 'Week(s)'), ('9', 'Month(s)')], default='1', max_length=2, verbose_name='Unit')),
                ('direction', models.CharField(choices=[('1', 'Up'), ('2', 'Down')], default='1', max_length=1, verbose_name='Direction')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight')),
                ('reporting_period', models.CharField(choices=[('1', 'Monthly'), ('2', 'Bi-Monthly'), ('3', 'Quarterly'), ('4', 'Semi-Annually'), ('5', 'Annually')], default='5', max_length=1, verbose_name='Reporting Period')),
                ('calculation', models.CharField(choices=[('1', 'Sum'), ('2', 'Average')], default='1', max_length=1, verbose_name='Calculation')),
                ('reporting_method', models.CharField(choices=[('1', 'Manual'), ('2', 'Automated')], default='1', max_length=1, verbose_name='Reporting Method')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer', verbose_name='Customer')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategy.Objective', verbose_name='Objective')),
            ],
            options={
                'verbose_name': 'KPI',
                'ordering': ['name', '-weight'],
                'verbose_name_plural': 'KPIs',
            },
        ),
    ]
