# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_auto_20170331_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['perspective', 'name', '-weight'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.AlterField(
            model_name='kpi',
            name='direction',
            field=models.CharField(choices=[('1', 'Up'), ('2', 'Down')], default='1', max_length=1, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='measure',
            field=models.TextField(max_length=255, verbose_name='Measure'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Key Performance Indicator'),
        ),
    ]
