# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:07
from __future__ import unicode_literals

import core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpis', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('file', models.FileField(max_length=255, upload_to=core.utils.PathAndRename('files/evidence/2017/'), verbose_name='File')),
            ],
            options={
                'verbose_name': 'Evidence',
                'ordering': ['name'],
                'verbose_name_plural': 'Evidences',
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpis.KPI', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'Initiative',
                'ordering': ['-date'],
                'verbose_name_plural': 'Initiatives',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=64, verbose_name='Value')),
                ('review_round', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Review Round')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpis.KPI', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'Score',
                'ordering': ['-date'],
                'verbose_name_plural': 'Scores',
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('year', models.PositiveIntegerField(default=2017, validators=[django.core.validators.MinValueValidator(2012), django.core.validators.MaxValueValidator(3000)], verbose_name='Year')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Scorecard',
                'ordering': ['year', 'name'],
                'verbose_name_plural': 'Scorecards',
            },
        ),
        migrations.CreateModel(
            name='ScorecardKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='The KPI BSC score', max_digits=64, verbose_name='Score')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpis.KPI', verbose_name='KPI')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scorecards.Scorecard', verbose_name='Scorecard')),
            ],
            options={
                'verbose_name': 'Scorecard KPI',
                'ordering': ['scorecard', 'kpi'],
                'verbose_name_plural': 'Scorecard KPIs',
            },
        ),
        migrations.AddField(
            model_name='scorecard',
            name='kpis',
            field=models.ManyToManyField(blank=True, through='scorecards.ScorecardKPI', to='kpis.KPI', verbose_name='KPIs'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='score',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scorecards.Scorecard', verbose_name='Scorecard'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scorecards.Scorecard', verbose_name='Scorecard'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scorecards.Scorecard', verbose_name='Scorecard'),
        ),
    ]
