# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Performance achieved as a percentage of the target', max_digits=64, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpis.KPI', verbose_name='KPI'),
        ),
    ]
