# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0002_auto_20170411_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecardkpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpis.KPI', verbose_name='KPI'),
        ),
        migrations.AlterField(
            model_name='scorecardkpi',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecards.Scorecard', verbose_name='Scorecard'),
        ),
    ]
