# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0003_auto_20170331_1604'),
        ('scorecards', '0002_auto_20170331_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='The KPI BSC score', max_digits=64, verbose_name='Score')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpis.KPI', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'Scorecard KPI',
                'ordering': ['scorecard', 'kpi'],
                'verbose_name_plural': 'Scorecard KPIs',
            },
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['name'], 'verbose_name': 'Evidence', 'verbose_name_plural': 'Evidences'},
        ),
        migrations.AlterModelOptions(
            name='initiative',
            options={'ordering': ['-date'], 'verbose_name': 'Initiative', 'verbose_name_plural': 'Initiatives'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-date'], 'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AlterModelOptions(
            name='scorecard',
            options={'ordering': ['year', 'name'], 'verbose_name': 'Scorecard', 'verbose_name_plural': 'Scorecards'},
        ),
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='kpis',
            field=models.ManyToManyField(blank=True, through='scorecards.ScorecardKPI', to='kpis.KPI', verbose_name='KPIs'),
        ),
        migrations.AddField(
            model_name='scorecardkpi',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scorecards.Scorecard', verbose_name='Scorecard'),
        ),
    ]
