# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0003_auto_20170412_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
