# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scorecards', '0004_scorecard_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='approval_note',
            field=models.TextField(blank=True, default='', verbose_name='Approval Note'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
