# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0005_auto_20170825_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
    ]
